name: .NET

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

on:
  push:
    tags:
      - "vRelease*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: pack
      run: | 
        cd src     
        dotnet tool restore
        dotnet r pack
        

    - name: push to nuget
      run: |
          dotnet nuget push ${{github.workspace}}/src/RSCG_Static/PACK/*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json

